server:
  port: 3000
spring:
  application:
    name: wyn-crowd-redis
  redis:
    host: 192.168.10.100
    pool: 6379
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka